config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :edit, :create, :destroy] do
      resources :comments, only: [:index, :show, :new, :edit, :create, :destroy]
      resources :likes, only: [:index, :show, :new, :edit, :create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  def update_comments_counter
    Post.increment_counter(:comments_counter, post_id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  def update_likes_counter
    Post.increment_counter(:likes_counter, post_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(3)
  end

  private

  def update_posts_counter
    User.increment_counter(:posts_counter, author_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true

  # PostsCounter must be an integer greater than or equal to zero
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  # returns the 3 most recent posts for a given user.
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:article_id])
    @comment = @post.comments.create(comment_params)
    redirect_to user_post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create
    redirect_to user_posts_url(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = @post.likes.find(params[:id])
    @like.destroy
    redirect_to user_posts_url(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(article_params)

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_url do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text %><br>
    <% post.errors.full_messages_for(:text).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<%= link_to "Back", user_path(id: params[:user_id]), class: 'bg-gray-500 rounded-sm text-white self-start p-1 mb-2' %>
<section class="w-full flex items-center gap-2 border-2 p-4">
  <img class="w-24 h-24" src=<%= User.find(params[:user_id]).photo %> alt=<%= User.find(params[:user_id]).name %> />
  <div>
  <p>Name: <%= User.find(params[:user_id]).name %></p>
  <p>Number of posts: <%= User.find(params[:user_id]).posts_counter %></p>
  </div>
</section>
<button class="bg-blue-500 text-white p-2 my-1" type="button">
  <%= link_to 'New Post', new_user_post_path %>
<button>
<ul class="w-full flex flex-col gap-2 p-4">
  <% @posts.each do |post| %>
    <li class="border-2 p-2">
      <div>
        <p class="text-md font-semibold">Post #<%= post.id %>: <%= post.title %></p>
        <p><%= post.text %></p>
        <div class="w-3/6 flex items-center gap-8">
          <p>Comments: <%= post.comments_counter %></p>
          <p>Likes: <%= post.likes_counter %></p>
        </div>
      </div>
      <ul class="w-full flex flex-col gap-2 p-4">
        <% post.recent_comments.each do |comment| %>
          <li class="border-2 p-2"><%= User.find(comment.author_id).name %>: <%= comment.text %></li>
        <% end %>
      </ul>
      <%= link_to "See Post", user_post_path(user_id: params[:user_id], id: post.id), class: 'bg-blue-500 rounded-sm self-center text-white p-1' %>
      <button>Next</button>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= link_to "Back", user_posts_path, class: 'bg-gray-500 rounded-sm text-white self-start p-1 mb-2' %>
<div class="w-full flex flex-col gap-2 p-4 border-2 p-2">
  <div>
    <p class="text-md font-semibold">Post #<%= @post.id %> by <%= User.find(@post.author_id).name %></p>
    <div class="w-3/6 flex items-center gap-8">
      <p>Comments: <%= @post.comments_counter %></p>
      <p>Likes: <%= @post.likes_counter %></p>
    </div>
  </div>
  <div>
    <h2 class="text-xl font-bold"><%= @post.title %></h2>
    <p><%= @post.text %></p>
  </div>
</div>
<div class="flex gap-2 items-center">
  <button class="bg-blue-500 text-white p-2 my-1" type="button">
  <button>
</div>
<ul class="w-full flex flex-col gap-2 p-4">
<% @post.recent_comments.each do |comment| %>
<li class="border-2 p-2">
  <p><%= User.find(comment.author_id).name %>: <%= comment.text %></p>
</li>
<% end %>
</ul>


<h1><%= @post.title %></h1>

<p><%= @post.text %></p>

<ul>
  <li><%= link_to "Edit", edit_user_post_path(@post) %></li>
  <li><%= link_to "Destroy", user_post_path(@post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/users/index.html.erb
<ul class="w-1/4 flex flex-col gap-4">
  <% @users.each do |user| %>
    <li class="flex items-center gap-2 border-2 p-4">
      <img class="w-24 h-24" src=<%=user.photo %> alt=<%= user.name %> />
      <div class="flex flex-col gap-1 items-start">
        <p>Name: <%= user.name %></p>
        <p>Number of posts: <%= user.posts_counter %></p>
        <%= link_to "More", user_path(id: user.id), class: 'bg-blue-500 rounded-sm text-white p-1' %>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<main>
  <section>
    <div class="card">
      <div class="user-image border"></div>
      <div class="user-image border">
        <img src="<%=@user.photo %>">            
      </div>
      <div class="user-data border">
        <h1><%= @user.name %></h1>
        <p class="number-posts">Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
    <div class="card">
      <div class="column">
        <h3>Bio:</h3>
        <p><%= @user.bio %></p>
      </div>
    </div>
  </section>
  <section class="center">
    <ul>
      <% @user.recent_posts.each do |post| %>
        <%= link_to user_posts_path(@user) do %>
          <li class="card column hover">
            <h3 class="left"><%= post.title%></h3>
            <h4 class="left"><%= post.text%></h4>
            <div class="right">
              <span>Comments: <%= post.comments_counter %></span>
              <span class="left">Likes: <%= post.likes_counter %> </span>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn" %>
  </section> 
</main>